apiVersion: v1
kind: Pod
metadata:
    name: hostpath-pod
spec:
   volumes:
    - name: hostpath-vol
      hostPath:
          path: /var/tmp
   containers:
    - name: hostpath-pod
      image: busybox
      command: ["/bin/sh","-c","echo Hello Sir, this is Sample File for HostVolume - $(date) >> /output/output.txt "]
      volumeMounts:
        - name: hostpath-vol
          mountPath: /output
