apiVersion: v1
kind: Pod
metadata:
    name: nginx-webproxy
    labels:
       app: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
         - name: nginx-port
           containerPort: 80
