apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    type: NodePort
    selector:
        app: nginx-pod
    ports:
     - protocol: TCP
       port: 80
       nodePort: 31010
       targetPort: nginx-port
       protocol: TCP
